### ISSUE TITLE
🛠New Storybook website 

### ISSUE THREAD

**Issue by domyen** [storybooks/frontpage#1]
## New Storybook website
🎉Storybook is getting a brand new website. This ticket documents the project. 

If you want to help with the buildout let folks know in the comments. 

[**🖼 Design in Invision**](https://projects.invisionapp.com/share/CBP627YE7YX#/331888311_-Home) 
- It is interactive. You can click on links or just page through with arrow keys.
- There are videos/gifs in the design, but alas they don’t work in Invision. Those assets are linked in situ to give you an idea of what the interaction will be. (🎥[Hero](https://www.dropbox.com/s/jdrh37vq70rrn6g/storybook-hero-video.m4v?dl=0), [Build](https://www.dropbox.com/s/75xcib5q1u8e40p/storybook-workflow-build.m4v?dl=0), [Test](https://www.dropbox.com/s/2kz2qifun2s9xk5/storybook-workflow-test.m4v?dl=0), [Share](https://www.dropbox.com/s/ei3zy6ci1s1bxx8/storybook-workflow-share.m4v?dl=0))
- Storybook screenshots and animations are taken from the UI overhaul in v5

[**📄 Brief in Google docs**](https://docs.google.com/document/d/122ob0nC2iEiwLFaCcLGR3Csn6Uo3FzSeQKttDywVl4E/edit#)

| **Old**  | **New**  | 
|---|---|
| <img width="300" alt="screenshot 2018-11-16 16 58 12" src="https://user-images.githubusercontent.com/263385/49237758-e70bfa80-f3cc-11e8-9da9-ad639a0595d6.png">  | <img width="300" alt="screenshot 2018-11-16 16 57 38" src="https://user-images.githubusercontent.com/263385/49237772-f1c68f80-f3cc-11e8-8917-5a0eab848469.png"> 

## Goal
The goal is to help developers learn and understand why to use Storybook. Developers who land on the site are unfamiliar with Storybook, we need to convince them that using Storybook improves their lives and helps them ship great UI components faster.

<img width="400" alt="screenshot 2018-11-29 11 32 50" src="https://user-images.githubusercontent.com/263385/49236691-a7441380-f3ca-11e8-8a5a-91b3f6c0bf8e.png">

In 2018 **52%** of JavaScript developers have not heard of Storybook and **83%** haven't tried it. This project updates the website to showcase how developers build UI components with Storybook. 

The text and illustrations showcase Storybook's biggest benefits. These benefits are sourced from meetups, presentations, books, and blog posts from the community at large. 

## Deliverables
**Doing:** /index, /addons, /community, /use-cases, /support
**Not doing:** /docs

- Static site: an interactive responsive website 
- Design system: a reusable and extendable UI component library to make developing future websites straightforward

**Tech stack**
- Storybook
- React
- Gatsby
- Styled-components
- Netlify

**Contributors**
- @domyen (me)
- @tmeasday 
- @christopherstat (interested)
- @alexandrebodin (interested)
- @kylemh (interested)
- @dakebl (interested)
- You?

## Reviewers
Designed in collaboration with core maintainers @igor-dv, @ndelangen, @shilman, and @tmeasday. (Thanks for giving me the opportunity!) 

Cross-posted from Discord #maintainers (11/16) and #design (11/20).  

💬Say hi in [Discord #design](https://discord.gg/MdC3cd6).

**Shoutouts**
- @SachaG, the creator of the current logo and awesome designer for helping review these designs
- @aparajita, for great copy edits 
- @orta for reviewing designs and excellent feedback

**Comment by KeithMcKiernan** [comment]
@domyen The new design's look awesome, great job.

Would be more than happy to help out with the dev. 👍

**Comment by dakebl** [comment]
@domyen also happy to help. Could you provide some specific tasks for contributors to help with?

**Comment by domyen** [comment]
@dakebl Awesome! I'm prepping the project to make it easy for contributors now so expect some more action in the next few days. It seems like you know a bit more about Gatsby than I do (😅). I'd love a Gatsby best practices audit from a more knowledgeable source!

**Comment by dakebl** [comment]
That's great @domyen, thank you! I've only contributed and worked with Gatsby a little, but I'm happy to share anything that I do know 😆 Looking forward to helping out!

**Comment by domyen** [comment]
I updated the [issues](https://github.com/storybooks/frontpage/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) with tasks I could use help on. 

I think the process can be pretty lightweight:
1. Folks can claim the task by commenting on the issue
2. I'll assign the the task to someone
3. Open a PR to the storybooks/frontpage with a link to the issue #

**Comment by domyen** [comment]
Congrats everyone -- the website lives! Thank you @dakebl @Keraito @lucas-carl @tmeasday @isaac-martin @shilman!

I'm closing this issue; all bugs and features will be tracked in the remaining issues.
