### ISSUE TITLE
Get contributor count from GitHub

### ISSUE THREAD

**Issue by domyen** [storybooks/frontpage#10]
<img width="496" alt="screenshot 2018-12-13 18 25 42" src="https://user-images.githubusercontent.com/263385/49973820-9506c100-ff04-11e8-8699-e6f7ee92d943.png">

**Behavior**
- Get contributor count from GitHub asynchronously

[Relevant Storybook local URL](http://localhost:6006/?selectedKind=screens%2FCommunityScreen%2FCommunityHero&selectedStory=not%20subscribed&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)

**Comment by Keraito** [comment]
I tried my hand on this issue, but there's a limitation with the information that the Github API provides. 

The [contributors endpoint](https://developer.github.com/v3/repos/#list-contributors) only provides me 30 contributors (ordered on amount of activity) and the [repo stats endpoint](https://developer.github.com/v3/repos/statistics/#get-contributors-list-with-additions-deletions-and-commit-counts) provides me with 100 contributors, similar to what the [contributors page on gh shows](https://github.com/storybooks/storybook/graphs/contributors). I found [something on the GH forum](https://github.community/t5/GitHub-API-Development-and/API-Github-list-contributors/td-p/9631) that it might not be possible to replicate the number shown on a repo page which is quite unfortunate. 

Did someone else do this before and maybe know how to circumvent this issue through the API?

**Comment by domyen** [comment]
Thanks for trying this out @Keraito. I just tried querying the GitHub API using [this trick](https://stackoverflow.com/questions/44347339/github-api-how-efficiently-get-the-total-contributors-amount-per-repository). 

`curl -I "https://api.github.com/repos/storybooks/storybook/contributors?per_page=1"`

Where you ask for 1 contributor per page and count the number of pages. But it didn't give me the accurate count (maxed out at 399).

`
Link: <https://api.github.com/repositories/54173593/contributors?per_page=1&page=2>; rel="next", <https://api.github.com/repositories/54173593/contributors?per_page=1&page=399>; rel="last"
`

There may be API limitations for particularly expansive projects like Storybook. If so, we may have to hardcode this number. Curious if other folks have experience doing this with the GitHub API. 🤔

**Comment by lucas-carl** [comment]
@Keraito @domyen It turns out, that you have to add `anon=true` to the query, because github makes users over a count of 500 anonymous.
See: https://github.community/t5/GitHub-API-Development-and/API-Github-list-contributors/td-p/9631
Hope it helps.

**Comment by domyen** [comment]
Good suggestion! By adding `anon=true` I get:

`Link: <https://api.github.com/repositories/54173593/contributors?per_page=1&anon=true&page=2>; rel="next", <https://api.github.com/repositories/54173593/contributors?per_page=1&anon=true&page=656>; rel="last"`

This indicates there are 656 total contributors. GitHub reports 571.
<img width="167" alt="screenshot 2018-12-27 10 01 00" src="https://user-images.githubusercontent.com/263385/50484418-638afc80-09be-11e9-9462-dd1ade7e527a.png">

Seems like no matter what technique, we end up with a contributor count that users will think is incorrect. 

For now, I'd suggest leaving it vague at "+570 contributors" instead of trying to calculate the exact count. What do you think?

**Comment by dakebl** [comment]
What about scraping it from the page using cheerio and run it as the first step of `yarn build`, writing the result to a file (or to npm config), and referencing that in the code?

I raised a PR to show this in action: https://github.com/storybooks/frontpage/pull/18

**Comment by domyen** [comment]
@dakebl QAing this, any reason why this is showing a contributor count of 000 in Chromatic but not in my local Storybook?

- [In Chromatic](https://www.chromaticqa.com/snapshot?appId=5be26744d2f6250024a9117d&id=5c41e9526bf4e5002464bba2)
- [In Storybook (you have to run it)](http://localhost:6006/?selectedKind=screens%2FCommunityScreen%2FCommunityHero&selectedStory=default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)

**Comment by dakebl** [comment]
Hey @domyen, the only thing I could think of is that there is some sort of weird caching ,or race condition, that's preventing us from properly fetching the value from the package config.

To address this I've created a gatsby plugin ([gatsby-source-github-repo](https://github.com/dakebl/gatsby-source-github-repo)) to fetch the data from the github page, using gatsby's internal graphql api, and raised a  new PR (https://github.com/storybooks/frontpage/pull/20) that switches out our manual step for the plugin. 

Seems to be running fine in the [netlify preview](https://deploy-preview-20--dazzling-chandrasekhar-c337aa.netlify.com/community) but I'm not sure how to test using Chromatic. 
Would you mind testing it out and letting me know if it solves the issue?

**Comment by domyen** [comment]
@tmeasday should we just stub this data in for Chromatic since it's dynamic?

**Comment by tmeasday** [comment]
@domyen I think so, definitely

**Comment by dakebl** [comment]
They all seem to be working [In Chromatic](https://www.chromaticqa.com/snapshot?appId=5be26744d2f6250024a9117d&id=5c47c550ccb52e002457e410)., but I think we should reinstate the `+` in front of each component (as I had removed them all). What do you think? @domyen @tmeasday ?

**Comment by dakebl** [comment]
Shall we close this one now @domyen?

**Comment by domyen** [comment]
Yup, thanks for leading this Dale! 🙌
