### ISSUE TITLE
Get monthly installs from NPM

### ISSUE THREAD

**Issue by domyen** [storybooks/frontpage#11]
<img width="496" alt="screenshot 2018-12-13 18 25 42" src="https://user-images.githubusercontent.com/263385/49973858-c41d3280-ff04-11e8-8c76-9b570bbd458d.png">

**Behavior**
- Get/calculate monthly installs from NPM

[**Relevant Storybook URL**](http://localhost:6006/?selectedKind=screens%2FCommunityScreen%2FCommunityHero&selectedStory=not%20subscribed&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)

**Comment by dakebl** [comment]
@lucas-carl You should be able to use npm's own internal API for this: https://github.com/npm/registry/blob/master/docs/download-counts.md

**Comment by domyen** [comment]
@lucas-carl I added you as a collaborator to this repo, I'll assign you this ticket when the invite is accepted!

**Comment by lucas-carl** [comment]
@domyen So, of which NPM package(s) do we count the installs? Is it just the @storybook/cli package? Or should I calculate the sum of all @storybook/* packages?

**Comment by domyen** [comment]
@lucas-carl sum of all storybook framework packages:
- React
- React native
- Vue
- Angular
- Ember
- HTML
- Svelte
- Mithril
- Riot
