### ISSUE TITLE
Get latest blog posts from Medium

### ISSUE THREAD

**Issue by domyen** [storybooks/frontpage#15]
Retrieve the latest blog posts from [Storybook's Medium](https://medium.com/storybookjs).

This package might help:
https://github.com/nikolaevra/medium-get-latest-posts

**Comment by Keraito** [comment]
Taking a shot at this 😃

**Comment by Keraito** [comment]
Ran into some CORS related stuff as the official Medium's API has no read endpoint, so instead have to use https://medium.com/storybookjs/latest?format=json as also done in the package linked in the OG comment. 

I will try to get working on it again somewhere this week. Does someone have good tips for how to work around CORS in local development? I keep struggling with it 😢

**Comment by domyen** [comment]
Not sure, this [article](https://hackernoon.com/import-your-medium-feed-into-react-ceadbaf785c7) _might_ help?

**Comment by Keraito** [comment]
Hmm yeah, unfortunately, it seems unavoidable to have some 3rd server/service in between for local development. Thanks for the link, will check it out!

**Comment by tmeasday** [comment]
@Keraito -- this thing seems useful maybe? https://crossorigin.me

**Comment by dakebl** [comment]
@Keraito have you tried using [gatsby-source-medium](https://www.gatsbyjs.org/packages/gatsby-source-medium)?

**Comment by Keraito** [comment]
I tried it with the proxies from both @domyen and @tmeasday but with little success. That Gatsby plugin looks promising yeah, will try it with that @dakebl!

**Comment by domyen** [comment]
@Keraito How's it going - need a hand?

**Comment by isaac-martin** [comment]
Can also help if needed
