### ISSUE TITLE
Deploy to storybook.js.org

### ISSUE THREAD

**Issue by shilman** [storybooks/frontpage#26]
- [x] storybook as submodule (on `release/5.0` branch for now)
- [x] build the docs under `/docs` on each deploy
   - https://github.com/storybooks/storybook/pull/5632
   - https://github.com/storybooks/frontpage/pull/27
- [ ] redirects for the old top-level URLs
  - [x] start with 302
  - [ ] change to 301 once tested
- [x] trigger a build by webhook on each storybook commit

**Comment by domyen** [comment]
@shilman, the new site is out, is this issue done?

**Comment by shilman** [comment]
I'll do the 301s now and close
