### ISSUE TITLE
Hook up mailing list form

### ISSUE THREAD

**Issue by domyen** [storybooks/frontpage#3]
@tmeasday volunteered to help out 🙏

- [ ] Make [MailinglistSubscribeForm](http://localhost:6006/?selectedKind=layout%2FMailingListSubscribeForm&selectedStory=basic&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) submission and errors self-contained
~- [ ] Setup mocks for StaticQuery in Gatsby. Or if that's not the right way to do things, please recommend a way :D~
- [x] Setup eslint
- [x] fix eslint errors and turn on for yarn test
- [x] Turn pure pages from Storybook into Gatsby pages
- [x] Setup Chromatic (this doesn't seem to work Dec 17 5:00PM ET)
- [x] Setup Netlify for SB deploy

**Comment by tmeasday** [comment]
@domyen eslint added. Do you want me to fix the problems?

**Comment by tmeasday** [comment]
Chromatic is working again

**Comment by tmeasday** [comment]
@domyen I fixed a lot of the linting but not all of it. Maybe you can have a stab at it? Run `yarn lint` to see the remaining 136 problems

**Comment by tmeasday** [comment]
I created the netlify site here: https://app.netlify.com/sites/happy-tesla-010e19/overview it seems to have even more problems

**Comment by tmeasday** [comment]
I think everything is sorted apart from the mailinglist form.

**Comment by domyen** [comment]
@tmeasday did you ever get around to hooking up the `MailingListForm`?

**Comment by tmeasday** [comment]
Yes, didn't I?

**Comment by isaac-martin** [comment]
Is this mailchimp? Looks like it? Netlify have lambda functions so we can hit the API, happy to refactor to do that if easier?

**Comment by tmeasday** [comment]
@isaac-martin I'm not quite sure what you mean but sure, if you want to send PR!
