### ISSUE TITLE
SSL Cert Failure

### ISSUE THREAD

**Issue by helenvholmes** [storybooks/frontpage#35]
It looks like there is either a configuration error or a DNS change that hasn't propagated properly yet for https://storybook.js.org/. As of 4/26 you're getting this error from Chrome: 

<img width="485" alt="Storybook SSL failure" src="https://user-images.githubusercontent.com/1720093/56825170-71df0d00-6826-11e9-8acb-f165b69146fd.png">

**Comment by shilman** [comment]
Not seeing this in my browsers or on SSL check. Can you double-check your connection @helenvholmes ?

https://www.ssllabs.com/ssltest/analyze.html?d=storybook.js.org

**Comment by helenvholmes** [comment]
Weird, I'm not getting it anymore either—I'll close this out, sorry for the issue noise.
