### ISSUE TITLE
Fix console errors and warnings

### ISSUE THREAD

**Issue by domyen** [storybooks/frontpage#4]
Audit components and fix console errors and warnings.

**Comment by isaac-martin** [comment]
I can do this also if wanted. Do we need to log elsewhere or are they leftover Dev testing logs

**Comment by domyen** [comment]
@isaac-martin that'd be awesome. It's definitely wanted and appreciated 🙏 

No need to log elsewhere right now.

**Comment by dakebl** [comment]
Can this be closed now @domyen @isaac-martin?

**Comment by domyen** [comment]
Closing. If someone finds a warning or error they can make another issue :D
