### ISSUE TITLE
Storybook + Gatsby: Staticquery could not be fetched 

### ISSUE THREAD

**Issue by domyen** [storybooks/frontpage#43]
There is a StaticQuery error wherever we use `useSiteMetadata()` which queries GraphQL. This appears like best practices in Gatsby but is not working in our Storybook. 

**Error**
> The result of this StaticQuery could not be fetched. This is likely a bug in Gatsby and if refreshing the page does not fix it, please open an issue in https://github.com/gatsbyjs/gatsby/issues

In Gatsby's issue tracker 👉 https://github.com/gatsbyjs/gatsby/issues/10662

**Repro**
1. Clone /frontpage
2. `yarn install && yarn build && yarn run storybook`
3. Go to [IndexScreen:default](http://localhost:6007/?path=/story/frontpage-screens-indexscreen-indexscreen--default) in Storybook

**More context**
The strange thing is that this behavior doesn't appear when Chromatic renders the component for some reason.  

Anyone seen this before? cc @tmeasday @dakebl @isaac-martin

**Comment by dakebl** [comment]
Hey @domyen, I looked into it and it makes sense. Gatsby provides static files that are created during the initial compilation of the build process, which is when the GraphQL queries are run. This means that the data collected from the query has already been used to write the file that will be served as part of the production app. 

In the Storybook context however, we render the component in isolation and therefore forego the initial compilation that hydrates the component with data.

I did find an old post that fixed this issue: https://github.com/gatsbyjs/gatsby/issues/12007#issuecomment-467730610

This short of it being that adding `babel-plugin-remove-graphql-queries` (as we have in our webpack config) will remove the GraphQL queries all together but only when the `NODE_ENV` is set to `production`. Storybook sets the `NODE_ENV` to `development` by default, so we can fix this by updating the npm scripts to set `NODE_ENV`:

```js
{
    "storybook": "NODE_ENV=production start-storybook -p 6006 -s static",
    "build-storybook": "NODE_ENV=production build-storybook -s static",
}
```
*Before*
![image](https://user-images.githubusercontent.com/20845740/57989303-a4300300-7a90-11e9-83f4-34d067c24512.png)

*After*
![image](https://user-images.githubusercontent.com/20845740/57989283-7c409f80-7a90-11e9-9329-4c91ee04de8f.png)

**Comment by tmeasday** [comment]
🙌

**Comment by domyen** [comment]
@dakebl You're a LEGEND! 👏

**Comment by dakebl** [comment]
Glad I could help 😄

**Comment by T04435** [comment]
Adding : `NODE_ENV=production` did not sove the issue for me.

```
"gatsby": "^2.24.66",
"storybook": "^6.0.28",
"storybook": "NODE_ENV=production start-storybook -p 6006 --no-dll  -s public",
"build-storybook": "NODE_ENV=production build-storybook --no-dll  -s public"
```

**Comment by laneparton** [comment]
In case anyone else finds this looking for answers, I finally was able to resolve the issue with a combination of:

1. https://github.com/gatsbyjs/gatsby/issues/26099#issuecomment-785821013
2. https://github.com/storybookjs/frontpage/issues/43#issuecomment-493798728

**Comment by simongoot** [comment]
Follow this setup guide, solves many gatsby related issues, Links, Queries, etc:
https://www.gatsbyjs.com/docs/how-to/testing/visual-testing-with-storybook/#manual-configuration

**Comment by sjhomer** [comment]
As of today, attempting the steps @simongoot posted via the official Gatsby docs are not working for me, with Storybook v6.4.22 and Gatsby v4.12.1 on a basic gatsby starter.. Thankfully @patriziosotgiu solution listed above does work! 

It seems just forcing the `NODE_ENV` isn't enough to have `babel-plugin-remove-graphql-queries` leverage the built public Gatsby folder, and only forcing the plugin directly via config does the trick. 👍🏻
