### ISSUE TITLE
Video quality perf optimization

### ISSUE THREAD

**Issue by domyen** [storybooks/frontpage#7]
![screen recording 2018-12-13 at 06 14 pm](https://user-images.githubusercontent.com/263385/49973415-faf24900-ff02-11e8-8e32-57a6adb2eda6.gif)

**Behavior**
There are videos on the site at two quality levels. For smaller/mobile screens I want to load the lighter-weight video to decrease page load time. For larger/desktop screens I want to load the normal video because it's higher quality.

**Request**
Some way to load a specific video source depending on viewport size. Currently, I've exported videos at two quality levels:
- High: videos/storybook-workflow-build-optimized-lg.mp4
- Low: videos/storybook-workflow-build-optimized-sm.mp4

**Example stories**
- [UseCasesScreen](http://localhost:6006/?selectedKind=screens%2FIndexScreen%2FIndexScreen&selectedStory=default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)

**Comment by dakebl** [comment]
Can we add some simple vanilla viewport logic with `window.innerWidth`?
```javascript
const videoSize = (window.innerWidth > 600) ? 'lg' : 'sm';
<video autoPlay muted loop playsInline>
  <source src={`videos/storybook-workflow-build-optimized-${videoSize}.mp4`} type="video/mp4" />
</video>
```

Should probably make a `Video` component to isolate this logic and use the component in both `IndexScreen` and `Hero`

**Comment by domyen** [comment]
That proposal sounds like it could work! Want to have a go at it?

**Comment by dakebl** [comment]
On it 👍

**Comment by domyen** [comment]
Merged, much appreciated @dakebl 🙇‍♂️
