### ISSUE TITLE
Gatsby best practices audit

### ISSUE THREAD

**Issue by domyen** [storybooks/frontpage#9]
Would appreciate a Gatsby audit. 
- Are there low-hanging fruits we can do for speed/perf?
- Are there best practices that we should definitely adhere to?

[Deploy preview here](https://dazzling-chandrasekhar-c337aa.netlify.com/). PRs definitely welcome.

**Comment by jlengstorf** [comment]
Hey! 👋 

One quick win would be to use `gatsby-image` for the benefit images (e.g. [here](https://github.com/storybooks/frontpage/blob/f144fedbb95d003d0eb9403a16db98c799fec43a/src/components/screens/IndexScreen/IndexScreen.js#L73)).

Another thing that you _could_ do (though it’s certainly not required) is to add your config info to the `gatsby-config.js` as site metadata. This makes it queryable in GraphQL and has the benefit of centralizing all of the site config so future maintainers know where to look for it. One candidate would be https://github.com/storybooks/frontpage/blob/master/src/components/basics/shared/site.js — for reference, here’s how I manage site metadata on [my personal site](https://github.com/jlengstorf/lengstorf.com/blob/c1b0f7cf91210e84fbaa90561d33e4f9143e522c/gatsby-config.js#L66-L128).

To eliminate extra requests, you can inline SVGs by importing them. For example, in [this component](https://github.com/storybooks/frontpage/blob/f144fedbb95d003d0eb9403a16db98c799fec43a/src/components/layout/Header.js#L156) you could directly import the SVG
 instead. ([Example](https://github.com/jlengstorf/lengstorf.com/blob/c1b0f7cf91210e84fbaa90561d33e4f9143e522c/src/components/Beard.js#L4))

Overall this looks _really_ good. Excellent work!

Let me know if I can do anything else to help.

**Comment by dakebl** [comment]
Thank you @jlengstorf, for taking the time to take a look at the project and providing us with the suggestions! It's much appreciated 🙌 

I'm digging your [use-site-metadata.js](https://github.com/jlengstorf/gatsby-theme-jason-blog/blob/master/src/hooks/use-site-metadata.js) hook by the way. Using `useStaticQuery` to create custom query hooks is, \*_chef kiss_\*, beautiful. 

@domyen @tmeasday 
I'll change the SVG logic to use direct imports now.
I'll also move the site data into`gatsby-config.js` and update the relevant components to pull them from the page queries. Unless you can see a reason not to?

**Comment by dakebl** [comment]
Shall we close this one @domyen?
